export const GRADER_TEMPLATE = `
You are a grader. You are given a document and you need to evaluate the relevance of the documen with a user question.

Here is the retrieved document:

<document>
{document}
</document>

Here is the user question:

<question>
{question}
</question>

If the document contains keyword or semantic meaning related to the user question, then the document is relevant. Return a json reponse with key "relevant" and value true, if relevant, otherwise return false. So the response json key should be a boolean value.
`;

export const ANSWER_GRADER_TEMPLATE = `
You are a grader assistant. You are given a pair of a user question and a response generated by the LLM based on the vector store.

Here is the user question:
<question>
{question}
</question>

Here is the generated documents:
<answer>
{answer}
</answer>

If the answer is relevant to the user question, then return a json response with key "relevant" and value true, if relevant, otherwise return false. So the response json key should be a boolean value.`;